# Step 1: Build the application
FROM node:20-alpine AS builder

WORKDIR /base
COPY package.json .
COPY package-lock.json .
COPY ./api/package.json api/package.json
RUN npm i
COPY ./api api

RUN npm run build --workspace=api

EXPOSE 3000

ENTRYPOINT ["sh","api/start.sh"]